In [2]:
import numpy as np
import pandas as pd

## Reading Data From CSV File

In [3]:
train_detail_csv = pd.read_csv("Train-Detail-CSV.csv")    ##If Through Error then correclty Encode it by UTF or Latin 
train_detail_csv

   Unnamed: 0  Train-No  Speed    City
0           0      1122    160  Karachi
1           1      3344    220   Lahore
2           2      5566    320    Sindh

## Use of toList Method

In [4]:
print(repr(train_detail_csv.columns.tolist()))

['Unnamed: 0', 'Train-No', 'Speed', 'City ']

## Operation on Above CSV file

In [5]:
train_detail_csv['City ']  #Retrun Speed Column
# train_detail_csv['Speed']

0    Karachi
1     Lahore
2      Sindh
Name: City , dtype: object

In [6]:
train_detail_csv['Speed']  #Retrun Speed Column as a series

0    160
1    220
2    320
Name: Speed, dtype: int64

In [7]:
## Want to Update data
train_detail_csv['Speed'][0] = 160   #Give warning but update Data in file and in jupyter output

C:\Users\Rehman PC\AppData\Local\Temp\ipykernel_8564\3030870534.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  train_detail_csv['Speed'][0] = 160   #Give warning but update Data in file and in jupyter output

In [8]:
train_detail_csv

   Unnamed: 0  Train-No  Speed    City
0           0      1122    160  Karachi
1           1      3344    220   Lahore
2           2      5566    320    Sindh

In [9]:
# Again writing Updated content in file 
train_detail_csv.to_csv("Train-Detail-CSV.csv")

## Change Index

In [10]:
train_detail_csv.index = [1,2,3]
train_detail_csv

   Unnamed: 0  Train-No  Speed    City
1           0      1122    160  Karachi
2           1      3344    220   Lahore
3           2      5566    320    Sindh

In [11]:
train_detail_csv.index = ["First","Second","Third"]  #For String
train_detail_csv

        Unnamed: 0  Train-No  Speed    City
First            0      1122    160  Karachi
Second           1      3344    220   Lahore
Third            2      5566    320    Sindh

## Reading data from xlsx file

In [28]:
stu_data = pd.read_excel("students_data.xlsx")
stu_data

   ID    Name  Age Gender  Grade  Marks
0   1  Ayesha   17      F     11     85
1   2     Ali   18      M     12     90
2   3    Sana   16      F     10     78
3   4   Bilal   17      M     11     88
4   5  Fatima   16      F     10     92
5   6   Hamza   18      M     12     76

In [30]:
stu_data.dtypes

Subject          object
Max Marks         int64
Passing Marks     int64
dtype: object

In [29]:
# if u want to read sheet 2
stu_data = pd.read_excel("students_data.xlsx", sheet_name="Sheet2")
stu_data

    Subject  Max Marks  Passing Marks
0      Math        100             40
1   Science        100             40
2   English        100             40
3   History        100             40
4  Computer        100             40

## Writng Data in File

In [ ]:
# 1st Read sheet 1 then u are able to change to change in it
stu_data = pd.read_excel("students_data.xlsx", sheet_name="Sheet1")

In [38]:
stu_data

   ID    Name  Age Gender  Grade  Marks
0   1  Ayesha   17      F     11     85
1   2     Ali   18      M     12     90
2   3    Sana   16      F     10     78
3   4   Bilal   17      M     11     88
4   5   Obaid   16      F     10     92
5   6   Hamza   18      M     12     76

In [ ]:
stu_data.loc[stu_data["Name"] == "Fatima","Name"] = "Obaid" #Using Loc

In [ ]:
stu_data.iloc[0,1] = "Haroon"   #Using iloc

In [ ]:
stu_data.to_excel("students_data.xlsx", sheet_name="Sheet1")  #Writing Again in sheet1