In [ ]:
import numpy as np 
import pandas as pd

## Series(One dimensional with indices)

In [ ]:
series = pd.Series(np.random.rand(15))
series

0     0.741273
1     0.753042
2     0.287438
3     0.224636
4     0.535678
5     0.534727
6     0.211009
7     0.587641
8     0.400795
9     0.010082
10    0.049250
11    0.384215
12    0.119279
13    0.208986
14    0.522051
dtype: float64

In [ ]:
type(series)

pandas.core.series.Series

In [ ]:
series.dtypes

dtype('float64')

## Data Frame

In [ ]:
dataFrame = pd.DataFrame(np.random.rand(21,5))
dataFrame

           0         1         2         3         4
0   0.930934  0.375382  0.005174  0.794988  0.602943
1   0.988405  0.797114  0.053960  0.949516  0.094414
2   0.719877  0.582346  0.603938  0.677198  0.868033
3   0.517410  0.330182  0.428050  0.017043  0.988681
4   0.122467  0.645539  0.230169  0.018795  0.093232
5   0.231678  0.193640  0.959952  0.635500  0.908525
6   0.185118  0.428842  0.500730  0.060991  0.285330
7   0.663966  0.387667  0.907138  0.059975  0.218080
8   0.160921  0.575089  0.410075  0.942402  0.242741
9   0.975948  0.961556  0.050529  0.420259  0.660031
10  0.910658  0.550046  0.608894  0.265829  0.662210
11  0.255664  0.013825  0.615769  0.728603  0.443052
12  0.276956  0.999797  0.776362  0.120602  0.246895
13  0.488881  0.229248  0.311673  0.391885  0.721981
14  0.914493  0.997229  0.818740  0.675126  0.483318
15  0.100414  0.690754  0.105786  0.059941  0.889627
16  0.050573  0.757371  0.761677  0.052931  0.502247
17  0.102501  0.114324  0.944301  0.037172  0.441430
18  0.453177  0.915199  0.822270  0.136889  0.141323
19  0.808944  0.557895  0.820843  0.391406  0.759030
20  0.132693  0.124050  0.623440  0.275615  0.879035

## DataFrame Methods

In [ ]:
type(dataFrame)

pandas.core.frame.DataFrame

In [ ]:
dataFrame.dtypes

0    float64
1    float64
2    float64
3    float64
4    float64
dtype: object

In [ ]:
dataFrame[0]    #Return Series

0     0.930934
1     0.988405
2     0.719877
3     0.517410
4     0.122467
5     0.231678
6     0.185118
7     0.663966
8     0.160921
9     0.975948
10    0.910658
11    0.255664
12    0.276956
13    0.488881
14    0.914493
15    0.100414
16    0.050573
17    0.102501
18    0.453177
19    0.808944
20    0.132693
Name: 0, dtype: float64

In [ ]:
# Chnaging Data Type 
dataFrame[0][0] = "Abdul Rehman "    # In older version it was valid but now it will change but also throw warning

C:\Users\Rehman PC\AppData\Local\Temp\ipykernel_4216\1869320832.py:2: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value 'Abdul Rehman ' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  dataFrame[0][0] = "Abdul Rehman "    # In older version it was valid but now it will change but also throw warning

In [ ]:
dataFrame

                0         1         2         3         4
0   Abdul Rehman   0.375382  0.005174  0.794988  0.602943
1        0.988405  0.797114  0.053960  0.949516  0.094414
2        0.719877  0.582346  0.603938  0.677198  0.868033
3         0.51741  0.330182  0.428050  0.017043  0.988681
4        0.122467  0.645539  0.230169  0.018795  0.093232
5        0.231678  0.193640  0.959952  0.635500  0.908525
6        0.185118  0.428842  0.500730  0.060991  0.285330
7        0.663966  0.387667  0.907138  0.059975  0.218080
8        0.160921  0.575089  0.410075  0.942402  0.242741
9        0.975948  0.961556  0.050529  0.420259  0.660031
10       0.910658  0.550046  0.608894  0.265829  0.662210
11       0.255664  0.013825  0.615769  0.728603  0.443052
12       0.276956  0.999797  0.776362  0.120602  0.246895
13       0.488881  0.229248  0.311673  0.391885  0.721981
14       0.914493  0.997229  0.818740  0.675126  0.483318
15       0.100414  0.690754  0.105786  0.059941  0.889627
16       0.050573  0.757371  0.761677  0.052931  0.502247
17       0.102501  0.114324  0.944301  0.037172  0.441430
18       0.453177  0.915199  0.822270  0.136889  0.141323
19       0.808944  0.557895  0.820843  0.391406  0.759030
20       0.132693  0.124050  0.623440  0.275615  0.879035

In [ ]:
dataFrame.dtypes

0     object
1    float64
2    float64
3    float64
4    float64
dtype: object

In [ ]:
#Return Index Numbers
dataFrame.index

RangeIndex(start=0, stop=21, step=1)

In [ ]:
# Changing Data Frame To Numpy Array 
dataFrame.to_numpy()

array([['Abdul Rehman ', 0.37538152157885407, 0.005174464176715521,
        0.7949877817402569, 0.6029425605511709],
       [0.988405181454396, 0.7971136864443957, 0.053959653507858474,
        0.949516181609264, 0.0944141778640023],
       [0.7198765772557331, 0.5823460440380528, 0.6039377697292461,
        0.6771977873098376, 0.86803316308405],
       [0.5174098242435634, 0.33018163333611106, 0.42804957343384153,
        0.01704322113513823, 0.9886805940983544],
       [0.12246708315592925, 0.6455385222288251, 0.23016875651534363,
        0.018795094938428014, 0.0932320734417671],
       [0.23167816869076963, 0.1936397784998326, 0.9599524698298139,
        0.6354997788660095, 0.9085254761825007],
       [0.18511817071008985, 0.42884185640666095, 0.5007303762089962,
        0.060991389450030575, 0.28532997911567637],
       [0.6639660316394584, 0.38766701927164426, 0.90713826433529,
        0.059975445367972724, 0.21807976769279414],
       [0.16092124640266225, 0.5750888272112509, 0.4100748316300227,
        0.9424024713655061, 0.24274126724706901],
       [0.9759476716901574, 0.9615555228681993, 0.050529396177795505,
        0.4202594036555499, 0.6600311486637143],
       [0.9106582393220102, 0.5500461678135066, 0.6088943125423153,
        0.26582912251847, 0.6622098578859473],
       [0.25566424887450556, 0.013825460076729468, 0.6157689794868105,
        0.7286030690138722, 0.4430524758604659],
       [0.2769561940934139, 0.9997971673370812, 0.7763622600173449,
        0.12060219800384064, 0.24689478818056554],
       [0.4888807812792123, 0.22924824140676248, 0.31167320273330035,
        0.3918847066689912, 0.7219814566397995],
       [0.9144929491869969, 0.9972287479884774, 0.8187400567851165,
        0.6751258461145216, 0.4833182980108225],
       [0.10041420161733139, 0.6907540274531203, 0.10578634931966568,
        0.059941270470322494, 0.8896267492728986],
       [0.05057253935052486, 0.7573706461272051, 0.7616767012627398,
        0.05293050142328659, 0.5022471281401253],
       [0.10250080275643214, 0.11432398945114886, 0.9443009502733988,
        0.037172127297266044, 0.44143020400900523],
       [0.45317695254783286, 0.9151992485758041, 0.8222696824803436,
        0.13688884132132206, 0.14132277514948066],
       [0.8089440585629036, 0.5578952511755211, 0.8208434355093671,
        0.39140569013109416, 0.7590302846791583],
       [0.13269250247246533, 0.12405047841259309, 0.6234397452785809,
        0.27561455037201665, 0.8790347724202228]], dtype=object)

## Data Frame Attributes or Properties

In [ ]:
dataFrame.T #Take Transpose Of DataFrame

,0,1,2,3,4,5,6,7,8,9,...,11,12,13,14,15,16,17,18,19,20
0,Abdul Rehman,0.988405,0.719877,0.51741,0.122467,0.231678,0.185118,0.663966,0.160921,0.975948,...,0.255664,0.276956,0.488881,0.914493,0.100414,0.050573,0.102501,0.453177,0.808944,0.132693
1,0.375382,0.797114,0.582346,0.330182,0.645539,0.19364,0.428842,0.387667,0.575089,0.961556,...,0.013825,0.999797,0.229248,0.997229,0.690754,0.757371,0.114324,0.915199,0.557895,0.12405
2,0.005174,0.05396,0.603938,0.42805,0.230169,0.959952,0.50073,0.907138,0.410075,0.050529,...,0.615769,0.776362,0.311673,0.81874,0.105786,0.761677,0.944301,0.82227,0.820843,0.62344
3,0.794988,0.949516,0.677198,0.017043,0.018795,0.6355,0.060991,0.059975,0.942402,0.420259,...,0.728603,0.120602,0.391885,0.675126,0.059941,0.052931,0.037172,0.136889,0.391406,0.275615
4,0.602943,0.094414,0.868033,0.988681,0.093232,0.908525,0.28533,0.21808,0.242741,0.660031,...,0.443052,0.246895,0.721981,0.483318,0.889627,0.502247,0.44143,0.141323,0.75903,0.879035

In [ ]:
## Sorting Index
dataFrame.sort_index(axis=0,ascending=False)  #By Default Ascending True, axis=0 for rows

                0         1         2         3         4
20       0.132693  0.124050  0.623440  0.275615  0.879035
19       0.808944  0.557895  0.820843  0.391406  0.759030
18       0.453177  0.915199  0.822270  0.136889  0.141323
17       0.102501  0.114324  0.944301  0.037172  0.441430
16       0.050573  0.757371  0.761677  0.052931  0.502247
15       0.100414  0.690754  0.105786  0.059941  0.889627
14       0.914493  0.997229  0.818740  0.675126  0.483318
13       0.488881  0.229248  0.311673  0.391885  0.721981
12       0.276956  0.999797  0.776362  0.120602  0.246895
11       0.255664  0.013825  0.615769  0.728603  0.443052
10       0.910658  0.550046  0.608894  0.265829  0.662210
9        0.975948  0.961556  0.050529  0.420259  0.660031
8        0.160921  0.575089  0.410075  0.942402  0.242741
7        0.663966  0.387667  0.907138  0.059975  0.218080
6        0.185118  0.428842  0.500730  0.060991  0.285330
5        0.231678  0.193640  0.959952  0.635500  0.908525
4        0.122467  0.645539  0.230169  0.018795  0.093232
3         0.51741  0.330182  0.428050  0.017043  0.988681
2        0.719877  0.582346  0.603938  0.677198  0.868033
1        0.988405  0.797114  0.053960  0.949516  0.094414
0   Abdul Rehman   0.375382  0.005174  0.794988  0.602943

In [ ]:
dataFrame.sort_index(axis=1, ascending=False)  ## Axis 1 for columns

           4         3         2         1              0
0   0.602943  0.794988  0.005174  0.375382  Abdul Rehman
1   0.094414  0.949516  0.053960  0.797114       0.988405
2   0.868033  0.677198  0.603938  0.582346       0.719877
3   0.988681  0.017043  0.428050  0.330182        0.51741
4   0.093232  0.018795  0.230169  0.645539       0.122467
5   0.908525  0.635500  0.959952  0.193640       0.231678
6   0.285330  0.060991  0.500730  0.428842       0.185118
7   0.218080  0.059975  0.907138  0.387667       0.663966
8   0.242741  0.942402  0.410075  0.575089       0.160921
9   0.660031  0.420259  0.050529  0.961556       0.975948
10  0.662210  0.265829  0.608894  0.550046       0.910658
11  0.443052  0.728603  0.615769  0.013825       0.255664
12  0.246895  0.120602  0.776362  0.999797       0.276956
13  0.721981  0.391885  0.311673  0.229248       0.488881
14  0.483318  0.675126  0.818740  0.997229       0.914493
15  0.889627  0.059941  0.105786  0.690754       0.100414
16  0.502247  0.052931  0.761677  0.757371       0.050573
17  0.441430  0.037172  0.944301  0.114324       0.102501
18  0.141323  0.136889  0.822270  0.915199       0.453177
19  0.759030  0.391406  0.820843  0.557895       0.808944
20  0.879035  0.275615  0.623440  0.124050       0.132693

In [ ]:
type(dataFrame[0])

pandas.core.series.Series

## View(view in Pandas is like a pointer to the original data — changing it can also change the main data)

In [ ]:
view_dataFrame = dataFrame   ## view-df is View Of DF (view_Df Point to DF so where view-Df will be Changed Then Df will Also Change)

In [ ]:
view_dataFrame

                0         1         2         3         4
0   Abdul Rehman   0.375382  0.005174  0.794988  0.602943
1        0.988405  0.797114  0.053960  0.949516  0.094414
2        0.719877  0.582346  0.603938  0.677198  0.868033
3         0.51741  0.330182  0.428050  0.017043  0.988681
4        0.122467  0.645539  0.230169  0.018795  0.093232
5        0.231678  0.193640  0.959952  0.635500  0.908525
6        0.185118  0.428842  0.500730  0.060991  0.285330
7        0.663966  0.387667  0.907138  0.059975  0.218080
8        0.160921  0.575089  0.410075  0.942402  0.242741
9        0.975948  0.961556  0.050529  0.420259  0.660031
10       0.910658  0.550046  0.608894  0.265829  0.662210
11       0.255664  0.013825  0.615769  0.728603  0.443052
12       0.276956  0.999797  0.776362  0.120602  0.246895
13       0.488881  0.229248  0.311673  0.391885  0.721981
14       0.914493  0.997229  0.818740  0.675126  0.483318
15       0.100414  0.690754  0.105786  0.059941  0.889627
16       0.050573  0.757371  0.761677  0.052931  0.502247
17       0.102501  0.114324  0.944301  0.037172  0.441430
18       0.453177  0.915199  0.822270  0.136889  0.141323
19       0.808944  0.557895  0.820843  0.391406  0.759030
20       0.132693  0.124050  0.623440  0.275615  0.879035

In [ ]:
view_dataFrame[0][0] = 0.89756
dataFrame   #Change Will Occur here too

           0         1         2         3         4
0    0.89756  0.375382  0.005174  0.794988  0.602943
1   0.988405  0.797114  0.053960  0.949516  0.094414
2   0.719877  0.582346  0.603938  0.677198  0.868033
3    0.51741  0.330182  0.428050  0.017043  0.988681
4   0.122467  0.645539  0.230169  0.018795  0.093232
5   0.231678  0.193640  0.959952  0.635500  0.908525
6   0.185118  0.428842  0.500730  0.060991  0.285330
7   0.663966  0.387667  0.907138  0.059975  0.218080
8   0.160921  0.575089  0.410075  0.942402  0.242741
9   0.975948  0.961556  0.050529  0.420259  0.660031
10  0.910658  0.550046  0.608894  0.265829  0.662210
11  0.255664  0.013825  0.615769  0.728603  0.443052
12  0.276956  0.999797  0.776362  0.120602  0.246895
13  0.488881  0.229248  0.311673  0.391885  0.721981
14  0.914493  0.997229  0.818740  0.675126  0.483318
15  0.100414  0.690754  0.105786  0.059941  0.889627
16  0.050573  0.757371  0.761677  0.052931  0.502247
17  0.102501  0.114324  0.944301  0.037172  0.441430
18  0.453177  0.915199  0.822270  0.136889  0.141323
19  0.808944  0.557895  0.820843  0.391406  0.759030
20  0.132693  0.124050  0.623440  0.275615  0.879035

In [ ]:
view_dataFrame

           0         1         2         3         4
0    0.89756  0.375382  0.005174  0.794988  0.602943
1   0.988405  0.797114  0.053960  0.949516  0.094414
2   0.719877  0.582346  0.603938  0.677198  0.868033
3    0.51741  0.330182  0.428050  0.017043  0.988681
4   0.122467  0.645539  0.230169  0.018795  0.093232
5   0.231678  0.193640  0.959952  0.635500  0.908525
6   0.185118  0.428842  0.500730  0.060991  0.285330
7   0.663966  0.387667  0.907138  0.059975  0.218080
8   0.160921  0.575089  0.410075  0.942402  0.242741
9   0.975948  0.961556  0.050529  0.420259  0.660031
10  0.910658  0.550046  0.608894  0.265829  0.662210
11  0.255664  0.013825  0.615769  0.728603  0.443052
12  0.276956  0.999797  0.776362  0.120602  0.246895
13  0.488881  0.229248  0.311673  0.391885  0.721981
14  0.914493  0.997229  0.818740  0.675126  0.483318
15  0.100414  0.690754  0.105786  0.059941  0.889627
16  0.050573  0.757371  0.761677  0.052931  0.502247
17  0.102501  0.114324  0.944301  0.037172  0.441430
18  0.453177  0.915199  0.822270  0.136889  0.141323
19  0.808944  0.557895  0.820843  0.391406  0.759030
20  0.132693  0.124050  0.623440  0.275615  0.879035

## Copy(copy in Pandas is a separate duplicate of the data — changing it does not affect the original)

In [ ]:
Copy_dataFrame = dataFrame.copy() # Change Will Only Occur in copy_Df not in original dfIf u change something in copy_df

In [ ]:
dataFrame

           0         1         2         3         4
0    0.89756  0.375382  0.005174  0.794988  0.602943
1   0.988405  0.797114  0.053960  0.949516  0.094414
2   0.719877  0.582346  0.603938  0.677198  0.868033
3    0.51741  0.330182  0.428050  0.017043  0.988681
4   0.122467  0.645539  0.230169  0.018795  0.093232
5   0.231678  0.193640  0.959952  0.635500  0.908525
6   0.185118  0.428842  0.500730  0.060991  0.285330
7   0.663966  0.387667  0.907138  0.059975  0.218080
8   0.160921  0.575089  0.410075  0.942402  0.242741
9   0.975948  0.961556  0.050529  0.420259  0.660031
10  0.910658  0.550046  0.608894  0.265829  0.662210
11  0.255664  0.013825  0.615769  0.728603  0.443052
12  0.276956  0.999797  0.776362  0.120602  0.246895
13  0.488881  0.229248  0.311673  0.391885  0.721981
14  0.914493  0.997229  0.818740  0.675126  0.483318
15  0.100414  0.690754  0.105786  0.059941  0.889627
16  0.050573  0.757371  0.761677  0.052931  0.502247
17  0.102501  0.114324  0.944301  0.037172  0.441430
18  0.453177  0.915199  0.822270  0.136889  0.141323
19  0.808944  0.557895  0.820843  0.391406  0.759030
20  0.132693  0.124050  0.623440  0.275615  0.879035

In [ ]:
Copy_dataFrame[1][0] = 0.2345 #Column 0, row 1 (No Change will occur in original df)

C:\Users\Rehman PC\AppData\Local\Temp\ipykernel_4216\4168609694.py:1: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  Copy_dataFrame[1][0] = 0.2345 #Column 0, row 1 (No Change will occur in original df)
C:\Users\Rehman PC\AppData\Local\Temp\ipykernel_4216\4168609694.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  Copy_dataFrame[1][0] = 0.2345 #Column 0, row 1 (No Change will occur in original df)

In [ ]:
dataFrame #No Change will occur here

           0         1         2         3         4
0    0.89756  0.375382  0.005174  0.794988  0.602943
1   0.988405  0.797114  0.053960  0.949516  0.094414
2   0.719877  0.582346  0.603938  0.677198  0.868033
3    0.51741  0.330182  0.428050  0.017043  0.988681
4   0.122467  0.645539  0.230169  0.018795  0.093232
5   0.231678  0.193640  0.959952  0.635500  0.908525
6   0.185118  0.428842  0.500730  0.060991  0.285330
7   0.663966  0.387667  0.907138  0.059975  0.218080
8   0.160921  0.575089  0.410075  0.942402  0.242741
9   0.975948  0.961556  0.050529  0.420259  0.660031
10  0.910658  0.550046  0.608894  0.265829  0.662210
11  0.255664  0.013825  0.615769  0.728603  0.443052
12  0.276956  0.999797  0.776362  0.120602  0.246895
13  0.488881  0.229248  0.311673  0.391885  0.721981
14  0.914493  0.997229  0.818740  0.675126  0.483318
15  0.100414  0.690754  0.105786  0.059941  0.889627
16  0.050573  0.757371  0.761677  0.052931  0.502247
17  0.102501  0.114324  0.944301  0.037172  0.441430
18  0.453177  0.915199  0.822270  0.136889  0.141323
19  0.808944  0.557895  0.820843  0.391406  0.759030
20  0.132693  0.124050  0.623440  0.275615  0.879035

## Use Of Loc (loc is label-based (uses column/row names))

In [ ]:
view_dataFrame.loc[0,0] = 93215 # Now Dont thorw Warning
view_dataFrame.head(2)

          0         1         2         3         4
0     93215  0.375382  0.005174  0.794988  0.602943
1  0.988405  0.797114  0.053960  0.949516  0.094414

## Changing Names Of Columns

In [ ]:
view_dataFrame.columns = list("ABCDE")
view_dataFrame.head(2)

          A         B         C         D         E
0     93215  0.375382  0.005174  0.794988  0.602943
1  0.988405  0.797114  0.053960  0.949516  0.094414

In [ ]:
view_dataFrame.loc[0,0] = 0.654 # Now it will create another column name 0 coz now there is now column name 0 but we dont actually wanna do it
view_dataFrame.head(2)

          A         B         C         D         E      0
0     93215  0.375382  0.005174  0.794988  0.602943  0.654
1  0.988405  0.797114  0.053960  0.949516  0.094414    NaN

In [ ]:
view_dataFrame.loc[0,"A"] = 65454 #Now Change will occure rightly
view_dataFrame.head(2)

          A         B         C         D         E      0
0     65454  0.375382  0.005174  0.794988  0.602943  0.654
1  0.988405  0.797114  0.053960  0.949516  0.094414    NaN

In [ ]:
# Want to Drop Unncessary Column named 0
view_dataFrame = view_dataFrame.drop(0,axis=1)
view_dataFrame.head(2)

          A         B         C         D         E
0     65454  0.375382  0.005174  0.794988  0.602943
1  0.988405  0.797114  0.053960  0.949516  0.094414

## Want to select only Specific Rows Or Columns

In [ ]:
#Single Column
single_column = dataFrame['A']
print(single_column)

0        65454
1     0.988405
2     0.719877
3      0.51741
4     0.122467
5     0.231678
6     0.185118
7     0.663966
8     0.160921
9     0.975948
10    0.910658
11    0.255664
12    0.276956
13    0.488881
14    0.914493
15    0.100414
16    0.050573
17    0.102501
18    0.453177
19    0.808944
20    0.132693
Name: A, dtype: object

In [ ]:
# Multiple Columns
subset = dataFrame[['A','B']]
print(subset)

           A         B
0      65454  0.375382
1   0.988405  0.797114
2   0.719877  0.582346
3    0.51741  0.330182
4   0.122467  0.645539
5   0.231678  0.193640
6   0.185118  0.428842
7   0.663966  0.387667
8   0.160921  0.575089
9   0.975948  0.961556
10  0.910658  0.550046
11  0.255664  0.013825
12  0.276956  0.999797
13  0.488881  0.229248
14  0.914493  0.997229
15  0.100414  0.690754
16  0.050573  0.757371
17  0.102501  0.114324
18  0.453177  0.915199
19  0.808944  0.557895
20  0.132693  0.124050

In [ ]:
dataFrame.loc[[1,2],["C","D"]]  # Columns With Specific Rows

          C         D
1  0.053960  0.949516
2  0.603938  0.677198

In [ ]:
#Select All Rows But Specific Columns
view_dataFrame.loc[:,["C","D"]]

           C         D
0   0.005174  0.794988
1   0.053960  0.949516
2   0.603938  0.677198
3   0.428050  0.017043
4   0.230169  0.018795
5   0.959952  0.635500
6   0.500730  0.060991
7   0.907138  0.059975
8   0.410075  0.942402
9   0.050529  0.420259
10  0.608894  0.265829
11  0.615769  0.728603
12  0.776362  0.120602
13  0.311673  0.391885
14  0.818740  0.675126
15  0.105786  0.059941
16  0.761677  0.052931
17  0.944301  0.037172
18  0.822270  0.136889
19  0.820843  0.391406
20  0.623440  0.275615

In [ ]:
#Select All Columns But Specific Rows
view_dataFrame.loc[[1,2],:]

          A         B         C         D         E
1  0.988405  0.797114  0.053960  0.949516  0.094414
2  0.719877  0.582346  0.603938  0.677198  0.868033

## Rows Filtering

In [ ]:
# With single Condition 
view_dataFrame.loc[(view_dataFrame["A"]<0.3)] #Returns all rows of dataFrame where the value in column "A" is less than 0.3.

           A         B         C         D         E
4   0.122467  0.645539  0.230169  0.018795  0.093232
5   0.231678  0.193640  0.959952  0.635500  0.908525
6   0.185118  0.428842  0.500730  0.060991  0.285330
8   0.160921  0.575089  0.410075  0.942402  0.242741
11  0.255664  0.013825  0.615769  0.728603  0.443052
12  0.276956  0.999797  0.776362  0.120602  0.246895
15  0.100414  0.690754  0.105786  0.059941  0.889627
16  0.050573  0.757371  0.761677  0.052931  0.502247
17  0.102501  0.114324  0.944301  0.037172  0.441430
20  0.132693  0.124050  0.623440  0.275615  0.879035

In [ ]:
# With multiple Condition 
view_dataFrame.loc[(view_dataFrame["A"]<0.5) & ((view_dataFrame["C"]>0.2))] #Returns all rows of dataFrame where the value in column "A" is less than 0.3 and Value in Column C is > 0.1

           A         B         C         D         E
4   0.122467  0.645539  0.230169  0.018795  0.093232
5   0.231678  0.193640  0.959952  0.635500  0.908525
6   0.185118  0.428842  0.500730  0.060991  0.285330
8   0.160921  0.575089  0.410075  0.942402  0.242741
11  0.255664  0.013825  0.615769  0.728603  0.443052
12  0.276956  0.999797  0.776362  0.120602  0.246895
13  0.488881  0.229248  0.311673  0.391885  0.721981
16  0.050573  0.757371  0.761677  0.052931  0.502247
17  0.102501  0.114324  0.944301  0.037172  0.441430
18  0.453177  0.915199  0.822270  0.136889  0.141323
20  0.132693  0.124050  0.623440  0.275615  0.879035

## Use of Loc(iloc is position-based (uses integer indexes))

In [ ]:
view_dataFrame.head(4)

          A         B         C         D         E
0     65454  0.375382  0.005174  0.794988  0.602943
1  0.988405  0.797114  0.053960  0.949516  0.094414
2  0.719877  0.582346  0.603938  0.677198  0.868033
3   0.51741  0.330182  0.428050  0.017043  0.988681

In [ ]:
view_dataFrame.iloc[1,3]  # When want to acces

np.float64(0.949516181609264)

In [ ]:
view_dataFrame.iloc[[1,2],[2,1]]

          C         B
1  0.053960  0.797114
2  0.603938  0.582346

In [ ]:
view_dataFrame.head(3)

          A         B         C         D         E
0     65454  0.375382  0.005174  0.794988  0.602943
1  0.988405  0.797114  0.053960  0.949516  0.094414
2  0.719877  0.582346  0.603938  0.677198  0.868033

## Drop Rows and Columns

In [ ]:
#Drop row 
view_dataFrame.drop(0) #view_Df still remain same unless we dont do this like view_dataFrame = view_dataFrame.drop(0)

           A         B         C         D         E
1   0.988405  0.797114  0.053960  0.949516  0.094414
2   0.719877  0.582346  0.603938  0.677198  0.868033
3    0.51741  0.330182  0.428050  0.017043  0.988681
4   0.122467  0.645539  0.230169  0.018795  0.093232
5   0.231678  0.193640  0.959952  0.635500  0.908525
6   0.185118  0.428842  0.500730  0.060991  0.285330
7   0.663966  0.387667  0.907138  0.059975  0.218080
8   0.160921  0.575089  0.410075  0.942402  0.242741
9   0.975948  0.961556  0.050529  0.420259  0.660031
10  0.910658  0.550046  0.608894  0.265829  0.662210
11  0.255664  0.013825  0.615769  0.728603  0.443052
12  0.276956  0.999797  0.776362  0.120602  0.246895
13  0.488881  0.229248  0.311673  0.391885  0.721981
14  0.914493  0.997229  0.818740  0.675126  0.483318
15  0.100414  0.690754  0.105786  0.059941  0.889627
16  0.050573  0.757371  0.761677  0.052931  0.502247
17  0.102501  0.114324  0.944301  0.037172  0.441430
18  0.453177  0.915199  0.822270  0.136889  0.141323
19  0.808944  0.557895  0.820843  0.391406  0.759030
20  0.132693  0.124050  0.623440  0.275615  0.879035

In [ ]:
#Drop Column
view_dataFrame.drop(["A"],axis=1) #view_Df still remain same unless we dont do this like view_dataFrame = view_dataFrame.drop(["A"],axis=1)

           B         C         D         E
0   0.375382  0.005174  0.794988  0.602943
1   0.797114  0.053960  0.949516  0.094414
2   0.582346  0.603938  0.677198  0.868033
3   0.330182  0.428050  0.017043  0.988681
4   0.645539  0.230169  0.018795  0.093232
5   0.193640  0.959952  0.635500  0.908525
6   0.428842  0.500730  0.060991  0.285330
7   0.387667  0.907138  0.059975  0.218080
8   0.575089  0.410075  0.942402  0.242741
9   0.961556  0.050529  0.420259  0.660031
10  0.550046  0.608894  0.265829  0.662210
11  0.013825  0.615769  0.728603  0.443052
12  0.999797  0.776362  0.120602  0.246895
13  0.229248  0.311673  0.391885  0.721981
14  0.997229  0.818740  0.675126  0.483318
15  0.690754  0.105786  0.059941  0.889627
16  0.757371  0.761677  0.052931  0.502247
17  0.114324  0.944301  0.037172  0.441430
18  0.915199  0.822270  0.136889  0.141323
19  0.557895  0.820843  0.391406  0.759030
20  0.124050  0.623440  0.275615  0.879035

In [ ]:
view_dataFrame

           A         B         C         D         E
0      65454  0.375382  0.005174  0.794988  0.602943
1   0.988405  0.797114  0.053960  0.949516  0.094414
2   0.719877  0.582346  0.603938  0.677198  0.868033
3    0.51741  0.330182  0.428050  0.017043  0.988681
4   0.122467  0.645539  0.230169  0.018795  0.093232
5   0.231678  0.193640  0.959952  0.635500  0.908525
6   0.185118  0.428842  0.500730  0.060991  0.285330
7   0.663966  0.387667  0.907138  0.059975  0.218080
8   0.160921  0.575089  0.410075  0.942402  0.242741
9   0.975948  0.961556  0.050529  0.420259  0.660031
10  0.910658  0.550046  0.608894  0.265829  0.662210
11  0.255664  0.013825  0.615769  0.728603  0.443052
12  0.276956  0.999797  0.776362  0.120602  0.246895
13  0.488881  0.229248  0.311673  0.391885  0.721981
14  0.914493  0.997229  0.818740  0.675126  0.483318
15  0.100414  0.690754  0.105786  0.059941  0.889627
16  0.050573  0.757371  0.761677  0.052931  0.502247
17  0.102501  0.114324  0.944301  0.037172  0.441430
18  0.453177  0.915199  0.822270  0.136889  0.141323
19  0.808944  0.557895  0.820843  0.391406  0.759030
20  0.132693  0.124050  0.623440  0.275615  0.879035

## Use of inPlace (inplace=True in Pandas means change the original data directly instead of making a new copy)

In [ ]:
view_dataFrame.drop(["A"],axis=1, inplace=True)  #Now Change will occur in view_DataFrame

In [ ]:
view_dataFrame    #A got delete in view_Df

           B         C         D         E
0   0.375382  0.005174  0.794988  0.602943
1   0.797114  0.053960  0.949516  0.094414
2   0.582346  0.603938  0.677198  0.868033
3   0.330182  0.428050  0.017043  0.988681
4   0.645539  0.230169  0.018795  0.093232
5   0.193640  0.959952  0.635500  0.908525
6   0.428842  0.500730  0.060991  0.285330
7   0.387667  0.907138  0.059975  0.218080
8   0.575089  0.410075  0.942402  0.242741
9   0.961556  0.050529  0.420259  0.660031
10  0.550046  0.608894  0.265829  0.662210
11  0.013825  0.615769  0.728603  0.443052
12  0.999797  0.776362  0.120602  0.246895
13  0.229248  0.311673  0.391885  0.721981
14  0.997229  0.818740  0.675126  0.483318
15  0.690754  0.105786  0.059941  0.889627
16  0.757371  0.761677  0.052931  0.502247
17  0.114324  0.944301  0.037172  0.441430
18  0.915199  0.822270  0.136889  0.141323
19  0.557895  0.820843  0.391406  0.759030
20  0.124050  0.623440  0.275615  0.879035

In [ ]:
view_dataFrame.drop([0,5],axis=0, inplace=True)

In [ ]:
view_dataFrame

           B         C         D         E
1   0.797114  0.053960  0.949516  0.094414
2   0.582346  0.603938  0.677198  0.868033
3   0.330182  0.428050  0.017043  0.988681
4   0.645539  0.230169  0.018795  0.093232
6   0.428842  0.500730  0.060991  0.285330
7   0.387667  0.907138  0.059975  0.218080
8   0.575089  0.410075  0.942402  0.242741
9   0.961556  0.050529  0.420259  0.660031
10  0.550046  0.608894  0.265829  0.662210
11  0.013825  0.615769  0.728603  0.443052
12  0.999797  0.776362  0.120602  0.246895
13  0.229248  0.311673  0.391885  0.721981
14  0.997229  0.818740  0.675126  0.483318
15  0.690754  0.105786  0.059941  0.889627
16  0.757371  0.761677  0.052931  0.502247
17  0.114324  0.944301  0.037172  0.441430
18  0.915199  0.822270  0.136889  0.141323
19  0.557895  0.820843  0.391406  0.759030
20  0.124050  0.623440  0.275615  0.879035

## Reset Index

In [ ]:
view_dataFrame.reset_index() # But Reset Index Add and Extra Column

    index         B         C         D         E
0       1  0.797114  0.053960  0.949516  0.094414
1       2  0.582346  0.603938  0.677198  0.868033
2       3  0.330182  0.428050  0.017043  0.988681
3       4  0.645539  0.230169  0.018795  0.093232
4       6  0.428842  0.500730  0.060991  0.285330
5       7  0.387667  0.907138  0.059975  0.218080
6       8  0.575089  0.410075  0.942402  0.242741
7       9  0.961556  0.050529  0.420259  0.660031
8      10  0.550046  0.608894  0.265829  0.662210
9      11  0.013825  0.615769  0.728603  0.443052
10     12  0.999797  0.776362  0.120602  0.246895
11     13  0.229248  0.311673  0.391885  0.721981
12     14  0.997229  0.818740  0.675126  0.483318
13     15  0.690754  0.105786  0.059941  0.889627
14     16  0.757371  0.761677  0.052931  0.502247
15     17  0.114324  0.944301  0.037172  0.441430
16     18  0.915199  0.822270  0.136889  0.141323
17     19  0.557895  0.820843  0.391406  0.759030
18     20  0.124050  0.623440  0.275615  0.879035

In [ ]:
view_dataFrame.reset_index(drop=True, inplace=True)  # Now Extra column will be removed

In [ ]:
view_dataFrame

           B         C         D         E
0   0.797114  0.053960  0.949516  0.094414
1   0.582346  0.603938  0.677198  0.868033
2   0.330182  0.428050  0.017043  0.988681
3   0.645539  0.230169  0.018795  0.093232
4   0.428842  0.500730  0.060991  0.285330
5   0.387667  0.907138  0.059975  0.218080
6   0.575089  0.410075  0.942402  0.242741
7   0.961556  0.050529  0.420259  0.660031
8   0.550046  0.608894  0.265829  0.662210
9   0.013825  0.615769  0.728603  0.443052
10  0.999797  0.776362  0.120602  0.246895
11  0.229248  0.311673  0.391885  0.721981
12  0.997229  0.818740  0.675126  0.483318
13  0.690754  0.105786  0.059941  0.889627
14  0.757371  0.761677  0.052931  0.502247
15  0.114324  0.944301  0.037172  0.441430
16  0.915199  0.822270  0.136889  0.141323
17  0.557895  0.820843  0.391406  0.759030
18  0.124050  0.623440  0.275615  0.879035

## isNull method

In [ ]:
view_dataFrame["B"].isnull()

0     False
1     False
2     False
3     False
4     False
5     False
6     False
7     False
8     False
9     False
10    False
11    False
12    False
13    False
14    False
15    False
16    False
17    False
18    False
Name: B, dtype: bool

## Setting Values to None

In [ ]:
# view_dataFrame["B"] = None #Valid But Not Recommended
view_dataFrame.loc[:,["B"]] = None

C:\Users\Rehman PC\AppData\Local\Temp\ipykernel_4216\136124846.py:2: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value 'None' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  view_dataFrame.loc[:,["B"]] = None

In [ ]:
view_dataFrame["B"].isnull()

0     True
1     True
2     True
3     True
4     True
5     True
6     True
7     True
8     True
9     True
10    True
11    True
12    True
13    True
14    True
15    True
16    True
17    True
18    True
Name: B, dtype: bool

In [ ]:
view_dataFrame

       B         C         D         E
0   None  0.053960  0.949516  0.094414
1   None  0.603938  0.677198  0.868033
2   None  0.428050  0.017043  0.988681
3   None  0.230169  0.018795  0.093232
4   None  0.500730  0.060991  0.285330
5   None  0.907138  0.059975  0.218080
6   None  0.410075  0.942402  0.242741
7   None  0.050529  0.420259  0.660031
8   None  0.608894  0.265829  0.662210
9   None  0.615769  0.728603  0.443052
10  None  0.776362  0.120602  0.246895
11  None  0.311673  0.391885  0.721981
12  None  0.818740  0.675126  0.483318
13  None  0.105786  0.059941  0.889627
14  None  0.761677  0.052931  0.502247
15  None  0.944301  0.037172  0.441430
16  None  0.822270  0.136889  0.141323
17  None  0.820843  0.391406  0.759030
18  None  0.623440  0.275615  0.879035

## notNull() method

In [ ]:
view_dataFrame.notnull()   #Where null assing value to false where not null assign to true

        B     C     D     E
0   False  True  True  True
1   False  True  True  True
2   False  True  True  True
3   False  True  True  True
4   False  True  True  True
5   False  True  True  True
6   False  True  True  True
7   False  True  True  True
8   False  True  True  True
9   False  True  True  True
10  False  True  True  True
11  False  True  True  True
12  False  True  True  True
13  False  True  True  True
14  False  True  True  True
15  False  True  True  True
16  False  True  True  True
17  False  True  True  True
18  False  True  True  True

## New DataFrame

In [ ]:
new_dataFrame = pd.DataFrame({
    "name": ['Alfred', 'Batman', 'Catwoman'],
    "toy": [np.nan, 'Batmobile', 'Bullwhip'],
    "born": [pd.NaT, pd.Timestamp("1940-04-25"), pd.NaT]
})

In [ ]:
new_dataFrame

       name        toy       born
0    Alfred        NaN        NaT
1    Batman  Batmobile 1940-04-25
2  Catwoman   Bullwhip        NaT

## dropna Function

In [ ]:
new_dataFrame.dropna()

     name        toy       born
1  Batman  Batmobile 1940-04-25

## Use of how

In [ ]:
new_dataFrame.dropna(how="all") # delete row or columns unless all values are not na

       name        toy       born
0    Alfred        NaN        NaT
1    Batman  Batmobile 1940-04-25
2  Catwoman   Bullwhip        NaT

In [ ]:
new_dataFrame.dropna(how="any")   # If any value in row is na delete that row

     name        toy       born
1  Batman  Batmobile 1940-04-25

## New DataFrame_2

In [ ]:
new_dataFrame_2 = pd.DataFrame({
    "name": ['Alfred', 'Batman', 'Catwoman'],
    "toy": [np.nan, np.nan, np.nan],
    "born": [pd.NaT, pd.Timestamp("1940-04-25"), pd.NaT]
})

In [ ]:
new_dataFrame_2.dropna(how="all", axis=1)

       name       born
0    Alfred        NaT
1    Batman 1940-04-25
2  Catwoman        NaT

## New DataFrame_3

In [ ]:
new_dataFrame_3 = pd.DataFrame({
    "name": ['Alfred', 'Batman', 'Alfred'],
    "toy": [np.nan, 'Batmobile', 'Bullwhip'],
    "born": [pd.NaT, pd.Timestamp("1940-04-25"), pd.NaT]
})

## Use of value_counts

In [ ]:
new_dataFrame_3["name"].value_counts(dropna=False)    # Also keep na Value and count

name
Alfred    2
Batman    1
Name: count, dtype: int64

In [ ]:
new_dataFrame_3["toy"].value_counts(dropna=True)  #Remove na and count

toy
Batmobile    1
Bullwhip     1
Name: count, dtype: int64